# Generated by Django 3.1.5 on 2021-01-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='company_name',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='airline_company', to='mainapp.company'),
        ),
        migrations.AddField(
            model_name='airline',
            name='contact_number',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='airline_contact', to='mainapp.company'),
        ),
        migrations.AddField(
            model_name='airplane_manufacturer',
            name='company_name',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='airplane_manufacturer_company', to='mainapp.company'),
        ),
        migrations.AddField(
            model_name='airplane_manufacturer',
            name='contact_number',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='airplane_manufacturer_contact', to='mainapp.company'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airplane_manufacturer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='airline',
            unique_together={('company_name', 'contact_number')},
        ),
        migrations.AlterUniqueTogether(
            name='airplane_manufacturer',
            unique_together={('company_name', 'contact_number')},
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('company_name', 'contact_number')},
        ),
    ]
