# Generated by Django 3.1.5 on 2021-01-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('flight_number', 'leg_number', 'date', 'seat_number')},
        ),
    ]
