# Generated by Django 3.1.5 on 2021-01-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210123_1600'),
        ('mainapp', '0002_auto_20210123_1946'),
    ]

    operations = [
    ]
